### ISSUE TITLE
Url du Flash configurable par préférence portlet

### ISSUE THREAD

**Issue by jgribonvald** [GIP-RECIA/flash-info-portlet#1]
L'url n'est configurable que par préférence portlet. Et l'attribut de préférence est nommé flashUrl.

L'url peut contenir un pattern à remplacer par un attribut utilisateur, ce qui peut donner une url de la forme : https://my.domaine.fr/ctx/uri/{ESCOUAICourant}/autre, ce qui fait qu'il faut récupérer la chaîne entre { } pour obtenir l'attribut utilisateur à retourner. Si attribut non défini pour l'utilisateur alors ne pas traiter l'url, si attribut multivalué au lieu de monovalué idem ne pas traiter l'url. Mais aussi générer un log d'erreur avec les infos user et la cause.

**Comment by mcisse3007** [comment]
Fait, A valider.
